org: cruzlucas
app: first-project-aws
service: first-project-aws
frameworkVersion: '3'

custom:
  relatoriosBucket: '${self:service}-${self:provider.stage}-relatorios-bucket-lucascruz-${self:provider.region}'
  folder_bucket: '${param:folder_bucket, "relatorios"}/'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NOME_DESTINATARIO: ${param:NOME_DESTINATARIO}
    EMAIL_DESTINATARIO: ${param:EMAIL_DESTINATARIO}
    EMAIL_HOST_SMTP: ${param:EMAIL_HOST_SMTP}
    SENHA_HOST_SMTP: ${param:SENHA_HOST_SMTP}

functions:
  onUpload:
    handler: src/functions/uploadS3.onUpload
    events:
      - s3:
          bucket: ${self:custom.relatoriosBucket}
          event: s3:ObjectCreated:*
          rules:  
            - prefix: ${self:custom.folder_bucket}
            - suffix: .xls
          existing: true
      - s3:
          bucket: ${self:custom.relatoriosBucket}
          event: s3:ObjectCreated:*
          rules:  
            - prefix: ${self:custom.folder_bucket} 
            - suffix: .csv
          existing: true
      - s3:
          bucket: ${self:custom.relatoriosBucket}
          event: s3:ObjectCreated:*
          rules:  
            - prefix: ${self:custom.folder_bucket} 
            - suffix: .xlsx
          existing: true
    

resources:
  Resources:
    RelatoriosBucket:
        Type: AWS::S3::Bucket
        Properties: 
          BucketName: ${self:custom.relatoriosBucket}
          AccessControl: Private
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: RelatoriosBucket
        PolicyDocument: 
          Statement:
            -
              Effect: "Allow"
              Principal: "*"
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource:
                Fn::Join:
                  - ""
                  -
                    - "arn:aws:s3:::"
                    -
                      Ref: "RelatoriosBucket"
                    - "/*"
